name: 构建与发布

on:
  release:
    types: [created]
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        
      - name: 设置Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install requests bs4 lxml ebooklib tqdm
          
      - name: 确保cookie.json存在
        run: |
          if (-not (Test-Path -Path "./cookie.json")) {
            '""' | Out-File -FilePath "./cookie.json" -Encoding utf8
          }
          
      - name: 准备构建脚本
        run: |
          # 确保build_exe.py中包含ebooklib.epub
          (Get-Content build_exe.py) | ForEach-Object {
            if ($_ -match "--hidden-import=ebooklib',") {
              $_ -replace "--hidden-import=ebooklib',", "--hidden-import=ebooklib',`n    '--hidden-import=ebooklib.epub',  # 明确导入epub子模块"
            } else {
              $_
            }
          } | Set-Content build_exe.py
          
      - name: 构建Windows可执行文件
        run: |
          python build_exe.py
          
      - name: 压缩Windows可执行文件
        run: |
          Compress-Archive -Path dist/番茄小说下载器.exe -DestinationPath 番茄小说下载器-Windows.zip
          
      - name: 上传构建产物
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: 番茄小说下载器-Windows.zip
          
      - name: 上传至Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 番茄小说下载器-Windows.zip
          asset_name: 番茄小说下载器-Windows.zip
          tag: ${{ github.ref }}
          overwrite: true

  # 为MacOS构建
  build-macos:
    runs-on: macos-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        
      - name: 设置Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install requests bs4 lxml ebooklib tqdm
          
      - name: 确保cookie.json存在
        run: |
          if [ ! -f "./cookie.json" ]; then
            echo '""' > "./cookie.json"
          fi
          
      - name: 准备构建脚本
        run: |
          # 修改为macOS格式的路径分隔符
          sed -i '' 's/--add-data=2.py;./--add-data=2.py:./' build_exe.py
          sed -i '' 's/--add-data=cookie.json;./--add-data=cookie.json:./' build_exe.py
          
          # 确保包含ebooklib.epub
          if ! grep -q -- "--hidden-import=ebooklib.epub" build_exe.py; then
            sed -i '' 's/--hidden-import=ebooklib'"'"',/--hidden-import=ebooklib'"'"',\n    '"'"'--hidden-import=ebooklib.epub'"'"',  # 明确导入epub子模块/' build_exe.py
          fi
          
      - name: 构建MacOS可执行文件
        run: |
          python build_exe.py
          
      - name: 压缩MacOS可执行文件
        run: |
          cd dist && zip -r ../番茄小说下载器-MacOS.zip 番茄小说下载器
          
      - name: 上传构建产物
        uses: actions/upload-artifact@v3
        with:
          name: macos-build
          path: 番茄小说下载器-MacOS.zip
          
      - name: 上传至Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 番茄小说下载器-MacOS.zip
          asset_name: 番茄小说下载器-MacOS.zip
          tag: ${{ github.ref }}
          overwrite: true

  # 为Linux构建
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        
      - name: 设置Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install requests bs4 lxml ebooklib tqdm
          
      - name: 确保cookie.json存在
        run: |
          if [ ! -f "./cookie.json" ]; then
            echo '""' > "./cookie.json"
          fi
          
      - name: 准备构建脚本
        run: |
          # 修改为Linux格式的路径分隔符
          sed -i 's/--add-data=2.py;./--add-data=2.py:./' build_exe.py
          sed -i 's/--add-data=cookie.json;./--add-data=cookie.json:./' build_exe.py
          
          # 确保包含ebooklib.epub
          if ! grep -q -- "--hidden-import=ebooklib.epub" build_exe.py; then
            sed -i 's/--hidden-import=ebooklib'"'"',/--hidden-import=ebooklib'"'"',\n    '"'"'--hidden-import=ebooklib.epub'"'"',  # 明确导入epub子模块/' build_exe.py
          fi
          
      - name: 构建Linux可执行文件
        run: |
          python build_exe.py
          
      - name: 压缩Linux可执行文件
        run: |
          cd dist && zip -r ../番茄小说下载器-Linux.zip 番茄小说下载器
          
      - name: 上传构建产物
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: 番茄小说下载器-Linux.zip
          
      - name: 上传至Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 番茄小说下载器-Linux.zip
          asset_name: 番茄小说下载器-Linux.zip
          tag: ${{ github.ref }}
          overwrite: true